package com.texttomp3.texttospeech.utils

object Constants {
    const val AD_UNIT_ID_APP_OPEN_ADS = "ca-app-pub-3940256099942544/9257395921"
    const val AD_UNIT_ID_INTERSTITIAL_ADS = "ca-app-pub-3940256099942544/1033173712"
    const val AD_UNIT_ID_ADAPTIVE_BANNER_ADS = "ca-app-pub-3940256099942544/9214589741"
    const val AD_UNIT_ID_FIXED_SIZE_BANNER_ADS = "ca-app-pub-3940256099942544/6300978111"
    const val AD_UNIT_ID_REWARDED_ADS = "ca-app-pub-3940256099942544/5224354917"
    const val AD_UNIT_ID_REWARDED_INTERSTITIAL_ADS = "ca-app-pub-3940256099942544/5354046379"
    const val AD_UNIT_ID_NATIVE_ADS = "ca-app-pub-3940256099942544/2247696110"
    const val AD_UNIT_ID_NATIVE_VIDEO_ADS = "ca-app-pub-3940256099942544/1044960115"

    const val LINK_GOOGLE_PLAY = "https://play.google.com/store/apps/details?id="
    const val SET_PACKAGE = "com.android.vending"
    const val LINK_SEARCH_GOOGLE_PLAY = "https://play.google.com/store/search?q="
    const val QUERY_APP = "pub:Simpfox"
    const val EMAIL = "feedback.simpfox@gmail.com"

    const val LINK_TERM = "https://simpfox.com/privacy_policy.html"
    const val LINK_PRIVACY = "https://simpfox.com/privacy_policy.html"

    const val SUBSCRIPTION_PRODUCT_ID = "pro"
    const val SUBSCRIPTION_PRODUCT_ID_PRO_WEEK = "pro-w"
    const val SUBSCRIPTION_PRODUCT_ID_PRO_YEAR = "pro-y"
    const val SUBSCRIPTION_PRODUCT_ID_PRO_WEEK_TRIAL = "pro-w-t"
    const val SUBSCRIPTION_PRODUCT_ID_PRO_YEAR_TRIAL = "pro-y-t"

    const val IS_FIRST_OPEN_APP = "is first open app"
    const val MODE = "mode"
    const val LANGUAGE = "language"
    const val VOICE = "voice"
    const val ANDROID = "android"
    const val EDGE = "edge"
    const val PITCH = "pitch"
    const val SPEED = "speed"
    const val VOLUME = "volume"
    const val ID = "id"
    const val CONTENT = "content"
    const val FILE_PATH = "file_path"
    const val MALE = "Male"
    const val FEMALE = "Female"
    const val GB = "GB"
    const val NEW_TO_OLD = "new to old"
    const val OLD_TO_NEW = "old to new"
    const val A_Z = "a-z"
    const val Z_A = "z-a"
    const val LAST_MODIFIED = "Last modified"
    const val NAME = "Name"
    const val GENDER = "gender"
    const val VOICE_DEFAULT = "en-gb-x-gba-local"
    const val MORE_BOTTOM_SHEET = "more_bottom_sheet"
    const val MODE_BOTTOM_SHEET = "mode_bottom_sheet"
    const val LANGUAGE_BOTTOM_SHEET = "language_bottom_sheet"
    const val VOICE_BOTTOM_SHEET = "voice_bottom_sheet"
    const val RENAME_BOTTOM_SHEET = "rename_bottom_sheet"
    const val DELETE_BOTTOM_SHEET = "delete_bottom_sheet"
    const val THANK_BOTTOM_SHEET = "thank_bottom_sheet"
    const val RATE_BOTTOM_SHEET = "rate_bottom_sheet"
    const val HELLO = "hello"
    const val DISPLAY_INDEX = "display_index"
    const val PLAN = "plan"
    const val PRICE = "price"
    const val CYCLE = "cycle"
}